src/Entity/Projets.php
<?php

namespace App\Entity;

use App\Repository\ProjetsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProjetsRepository::class)]
class Projets
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $NomProjet = null;

    #[ORM\Column(length: 255)]
    private ?string $DescriptionProjet = null;

    #[ORM\ManyToOne(inversedBy: 'projets')]
    private ?Utilisateurs $Createur = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $DateCreation = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $DateModification = null;

    #[ORM\OneToMany(mappedBy: 'Projet', targetEntity: Taches::class)]
    private Collection $taches;

    public function __construct()
    {
        $this->taches = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomProjet(): ?string
    {
        return $this->NomProjet;
    }

    public function setNomProjet(string $NomProjet): static
    {
        $this->NomProjet = $NomProjet;

        return $this;
    }

    public function getDescriptionProjet(): ?string
    {
        return $this->DescriptionProjet;
    }

    public function setDescriptionProjet(string $DescriptionProjet): static
    {
        $this->DescriptionProjet = $DescriptionProjet;

        return $this;
    }

    public function getCreateur(): ?Utilisateurs
    {
        return $this->Createur;
    }

    public function setCreateur(?Utilisateurs $Createur): static
    {
        $this->Createur = $Createur;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->DateCreation;
    }

    public function setDateCreation(\DateTimeInterface $DateCreation): static
    {
        $this->DateCreation = $DateCreation;

        return $this;
    }

    public function getDateModification(): ?\DateTimeInterface
    {
        return $this->DateModification;
    }

    public function setDateModification(\DateTimeInterface $DateModification): static
    {
        $this->DateModification = $DateModification;

        return $this;
    }

    public function getslug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    public function __ToString(){
        return $this->NomProjet;
    }

    /**
     * @return Collection<int, Taches>
     */
    public function getTaches(): Collection
    {
        return $this->taches;
    }

    public function addTach(Taches $tach): static
    {
        if (!$this->taches->contains($tach)) {
            $this->taches->add($tach);
            $tach->setProjet($this);
        }

        return $this;
    }

    public function removeTach(Taches $tach): static
    {
        if ($this->taches->removeElement($tach)) {
            // set the owning side to null (unless already changed)
            if ($tach->getProjet() === $this) {
                $tach->setProjet(null);
            }
        }

        return $this;
    }

}

src/Entity/Taches.php
<?php

namespace App\Entity;

use App\Repository\TachesRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TachesRepository::class)]
class Taches
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $TitreTache = null;

    #[ORM\Column(length: 255)]
    private ?string $DescriptionTache = null;

    #[ORM\ManyToOne(inversedBy: 'taches')]
    private ?Statut $Statut = null;

    #[ORM\ManyToOne(inversedBy: 'taches')]
    private ?Projets $Projet = null;

    #[ORM\ManyToOne(inversedBy: 'taches')]
    private ?Utilisateurs $Utilisateur = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $DateCreation = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $DateEcheance = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitreTache(): ?string
    {
        return $this->TitreTache;
    }

    public function setTitreTache(string $TitreTache): static
    {
        $this->TitreTache = $TitreTache;

        return $this;
    }

    public function getDescriptionTache(): ?string
    {
        return $this->DescriptionTache;
    }

    public function setDescriptionTache(string $DescriptionTache): static
    {
        $this->DescriptionTache = $DescriptionTache;

        return $this;
    }

    public function getStatut(): ?Statut
    {
        return $this->Statut;
    }

    public function setStatut(?Statut $Statut): static
    {
        $this->Statut = $Statut;

        return $this;
    }

    public function getProjet(): ?Projets
    {
        return $this->Projet;
    }

    public function setProjet(?Projets $Projet): static
    {
        $this->Projet = $Projet;

        return $this;
    }

    public function getUtilisateur(): ?Utilisateurs
    {
        return $this->Utilisateur;
    }

    public function setUtilisateur(?Utilisateurs $Utilisateur): static
    {
        $this->Utilisateur = $Utilisateur;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->DateCreation;
    }

    public function setDateCreation(\DateTimeInterface $DateCreation): static
    {
        $this->DateCreation = $DateCreation;

        return $this;
    }

    public function getDateEcheance(): ?\DateTimeInterface
    {
        return $this->DateEcheance;
    }

    public function setDateEcheance(\DateTimeInterface $DateEcheance): static
    {
        $this->DateEcheance = $DateEcheance;

        return $this;
    }
}

src/Form/ProjetsType.php
<?php

namespace App\Form;

use App\Entity\Projets;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProjetsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('NomProjet')
            ->add('DescriptionProjet')
            ->add('DateCreation')
            ->add('DateModification')
            ->add('Createur')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Projets::class,
        ]);
    }
}

src/Controller/ProjetsController.php
<?php

namespace App\Controller;

use App\Entity\Projets;
use App\Entity\Taches;
use App\Form\ProjetsType;
use App\Repository\ProjetsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Service\Slugger;
use App\Repository\TachesRepository;

#[Route('/projets')]
class ProjetsController extends AbstractController
{
    #[Route('/', name: 'app_projets_index', methods: ['GET'])]
    public function index(ProjetsRepository $projetsRepository): Response
    {
        return $this->render('projets/index.html.twig', [
            'projets' => $projetsRepository->findAll(),
        ]);
    }

    #[Route('/choixprojet', name: 'app_projets_choix', methods: ['GET'])]
    public function ChoixProjet(ProjetsRepository $projetsRepository): Response
    {
        return $this->render('projets/selectprojet.html.twig', [
            'projets' => $projetsRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_projets_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $projet = new Projets();
        $form = $this->createForm(ProjetsType::class, $projet);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $slug = new Slugger();
            $projet->setSlug($slug->slugify($projet->getNomProjet()));
            $entityManager->persist($projet);
            $entityManager->flush();

            return $this->redirectToRoute('app_projets_choix', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('projets/new.html.twig', [
            'projet' => $projet,
            'form' => $form,
        ]);
    }

    #[Route('/{slug}', name: 'app_projets_kanban', methods: ['GET'])]
    public function kanban(Projets $projet, TachesRepository $tacherepository): Response
    {
        return $this->render('projets/kanban.html.twig', [
            'projet' => $projet,
            'taches' =>$tacherepository->findAll(),
        ]);
    }

    #[Route('/{id}', name: 'app_projets_show', methods: ['GET'])]
    public function show(Projets $projet): Response
    {
        return $this->render('projets/show.html.twig', [
            'projet' => $projet,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_projets_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Projets $projet, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ProjetsType::class, $projet);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_projets_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('projets/edit.html.twig', [
            'projet' => $projet,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_projets_delete', methods: ['POST'])]
    public function delete(Request $request, Projets $projet, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$projet->getId(), $request->request->get('_token'))) {
            $entityManager->remove($projet);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_projets_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/projets/_delete_form.html.twig
<form method="post" action="{{ path('app_projets_delete', {'id': projet.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ projet.id) }}">
    <button class="btn">Delete</button>
</form>

templates/projets/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Projets{% endblock %}

{% block body %}
    <h1>Edit Projets</h1>

    {{ include('projets/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_projets_index') }}">back to list</a>

    {{ include('projets/_delete_form.html.twig') }}
{% endblock %}

templates/projets/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Projets index{% endblock %}

{% block body %}
    <h1>Projets index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>NomProjet</th>
                <th>DescriptionProjet</th>
                <th>DateCreation</th>
                <th>DateModification</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for projet in projets %}
            <tr>
                <td>{{ projet.id }}</td>
                <td>{{ projet.NomProjet }}</td>
                <td>{{ projet.DescriptionProjet }}</td>
                <td>{{ projet.DateCreation ? projet.DateCreation|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ projet.DateModification ? projet.DateModification|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_projets_show', {'id': projet.id}) }}">show</a>
                    <a href="{{ path('app_projets_edit', {'id': projet.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_projets_new') }}">Create new</a>
    <a href="{{ path('app_projets_choix') }}">Choix Projet</a>
{% endblock %}

templates/projets/kanban.html.twig
{% extends 'base.html.twig' %}

{% block title %}Kanban{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{{asset('css/Kanban.css')}}">
    <script src="https://kit.fontawesome.com/db35c32846.js" crossorigin="anonymous"></script>
{% endblock %}

{% block body %}
    <a href="{{ path('app_projets_choix') }}">Revenir à la liste de projets</a>
    <!-- Simple MDL Progress Bar -->
<div class="kanban__title">
      <h1><i class="fa-solid fa-briefcase"></i> {{projet.NomProjet}} </h1>
</div>
<div class="dd">
  <ol class="kanban To-do">
    <div class="kanban__title">
      <h2><i class="fa-solid fa-triangle-exclamation"></i></i> A faire <a href="{{path('app_taches_new')}}"><button class="button-plus"><i class="fa-solid fa-plus"></i></button></a></h2>
      <div class="actions"></div>
    </div>
    {% for tache in taches %}
    {% if tache.statut == "A faire" %}
   <li class="dd-item" data-id="1">
      <h3 class="title dd-handle" >{{tache.TitreTache}}</h3>
        <div class="text"> {{tache.DescriptionTache}} </div>
        <div class="text" >Date de Création: {{ tache.DateCreation ? tache.DateCreation|date('d-m-Y') : '' }}</div>
        <div class="text" >Date d'échéance: {{tache.DateEcheance ? tache.DateEcheance|date('d-m-Y') : '' }}</div>
        <div class="actions"></div>
        <a href="{{path('app_taches_edit', {'id': tache.id})}}">Modifier</a>
    </li>
     {% endif %}
     {% endfor %}
  </ol>
  <ol class="kanban progress">
    <h2><i class="fa-solid fa-bars-progress"></i> En cours</h2>
    <div class="actions"></div>
    {% for tache in taches %}
    {% if tache.statut == "En cours" %}
      <li class="dd-item" data-id="5">
      <h3 class="title dd-handle">{{tache.TitreTache}}</h3>
        <div class="text" >{{tache.DescriptionTache}}</div>
        <div class="text" >Date de Création: {{ tache.DateCreation ? tache.DateCreation|date('d-m-Y') : '' }}</div>
        <div class="text" >Date d'échéance: {{tache.DateEcheance ? tache.DateEcheance|date('d-m-Y') : '' }}</div>
        <div class="actions"></div>
        <a href="{{path('app_taches_edit', {'id': tache.id})}}">Modifier</a>
    </li>
    {% endif %}
    {% endfor %}
  </ol>
  <ol class="kanban  Done">
  <h2><i class="fa-solid fa-thumbs-up"></i>   <i class="fa-solid fa-thumbs-down"></i> A tester</h2>
  <div class="actions"></div>
    {% for tache in taches %}
    {% if tache.statut == "A tester" %}
      <li class="dd-item" data-id="5">
      <h3 class="title dd-handle"> {{tache.TitreTache}}</h3>
        <div class="text" >{{tache.DescriptionTache}}</div>
        <div class="text" >Date de Création: {{ tache.DateCreation ? tache.DateCreation|date('d-m-Y') : '' }}</div>
        <div class="text" >Date d'échéance: {{tache.DateEcheance ? tache.DateEcheance|date('d-m-Y') : '' }}</div>
        <div class="actions"></div>
        <a href="{{path('app_taches_edit', {'id': tache.id})}}">Modifier</a>
    </li>
    
    {% endif %}
    {% endfor %}
  </ol>
  <ol class="kanban Gone">
    <h2><i class="fa-solid fa-circle-check"></i> Fini</h2>
    <div class="actions"></div>
    {% for tache in taches %}
    {% if tache.statut == "Fini" %}
     <li class="dd-item" data-id="5">
      <h3 class="title dd-handle">{{tache.TitreTache}}</h3>
        <div class="text" >{{tache.DescriptionTache}}</div>
        <div class="text" >Date de Création: {{ tache.DateCreation ? tache.DateCreation|date('d-m-Y') : '' }}</div>
        <div class="text" >Date d'échéance: {{tache.DateEcheance ? tache.DateEcheance|date('d-m-Y') : '' }}</div>
        <div class="actions"></div>
        <a href="{{path('app_taches_edit', {'id': tache.id})}}">Modifier</a>
    </li>
    {% endif %}
    {% endfor %}
  </ol>
</div>
    
{% endblock %}

templates/projets/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Projets{% endblock %}

{% block body %}
    <h1>Create new Projets</h1>

    {{ include('projets/_form.html.twig') }}

    <a href="{{ path('app_projets_index') }}">back to list</a>
{% endblock %}

templates/projets/selectprojet.html.twig
{% extends 'base.html.twig' %}

{% block title %}Select Projet{% endblock %}
{% block style %} <link rel="stylesheet" href="{{asset('css/SelectProjet.css')}}"> {% endblock %}
{% block body %}
    <h1>Choisi ton projet</h1>
    <ol style="--length: 100" role="list">
    {% set user = app.user.username %}
    {% for projet in projets %}
        {% if user == projet.createur %}
            <li style="--i: 100"><a href="{{path('app_projets_kanban', {'slug': projet.slug})}}">
                <h3>{{projet.NomProjet}}</h3>
                <p>{{projet.DescriptionProjet}}</p></a>
            </li>
        {% endif %}
    {% endfor %}
    </ol>
    <button><a href="{{path('app_projets_new')}}">Créer un nouveau projet</a></button>
{% endblock %}

templates/projets/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Projets{% endblock %}

{% block body %}
    <h1>Projets</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ projet.id }}</td>
            </tr>
            <tr>
                <th>NomProjet</th>
                <td>{{ projet.NomProjet }}</td>
            </tr>
            <tr>
                <th>DescriptionProjet</th>
                <td>{{ projet.DescriptionProjet }}</td>
            </tr>
            <tr>
                <th>DateCreation</th>
                <td>{{ projet.DateCreation ? projet.DateCreation|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>DateModification</th>
                <td>{{ projet.DateModification ? projet.DateModification|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_projets_index') }}">back to list</a>

    <a href="{{ path('app_projets_edit', {'id': projet.id}) }}">edit</a>

    {{ include('projets/_delete_form.html.twig') }}
{% endblock %}